import { Platform, StatusBar, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F7FAFC",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F7FAFC",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 40,
    paddingBottom: 20,
    backgroundColor: "#5E72E4",
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#FFF",
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  notificationIcon: {
    position: "relative",
  },
  notificationBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "#F56565",
    borderRadius: 10,
    width: 18,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  notificationBadgeText: {
    color: "#FFF",
    fontSize: 10,
    fontWeight: "bold",
  },
  logoutIcon: {
    marginLeft: 5,
  },
  scrollContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 100,
  },
  revenueRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    gap: 15,
  },
  revenueCard: {
    flex: 1,
    borderRadius: 15,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  dailyCard: {
    backgroundColor: "#5E72E4",
  },
  monthlyCard: {
    backgroundColor: "#38B2AC",
  },
  cardIconContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: 14,
    color: "#FFF",
    opacity: 0.9,
    marginBottom: 5,
  },
  cardAmount: {
    fontSize: 22,
    fontWeight: "700",
    color: "#FFF",
    marginBottom: 15,
  },
  cardFooter: {
    flexDirection: "row",
    alignItems: "center",
  },
  cardFooterText: {
    fontSize: 12,
    color: "#FFF",
    opacity: 0.8,
    marginLeft: 5,
  },
  servicesRow: {
    gap: 15,
    marginBottom: 20,
  },
  serviceCard: {
    borderRadius: 15,
    padding: 20,
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  pendingCard: {
    borderLeftWidth: 5,
    borderLeftColor: "#ED8936",
  },
  completedCard: {
    borderLeftWidth: 5,
    borderLeftColor: "#38A169",
  },
  serviceCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  serviceIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  serviceCardTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2D3748",
  },
  serviceCardCount: {
    fontSize: 28,
    fontWeight: "700",
    color: "#2D3748",
    marginBottom: 15,
  },
  serviceCardButton: {
    flexDirection: "row",
    alignItems: "center",
  },
  serviceCardButtonText: {
    color: "#5E72E4",
    fontSize: 14,
    fontWeight: "600",
    marginRight: 5,
  },
  bottomBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 12,
    paddingBottom: Platform.OS === "ios" ? 30 : 12,
    backgroundColor: "#FFF",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 5,
  },
  bottomButton: {
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  bottomButtonActive: {
    marginTop: -25,
    backgroundColor: "#5E72E4",
    borderRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 20,
    shadowColor: "#5E72E4",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  bottomButtonIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#EBF4FF",
  },
  bottomButtonIconActive: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  bottomButtonText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#718096",
    marginTop: 5,
  },
  bottomButtonTextActive: {
    color: "#FFF",
  },
  redDot: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: "red",
    width: 10,
    height: 10,
    borderRadius: 5,
    zIndex: 10,
  },
});
