import { StyleSheet, Platform, StatusBar } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: "#F7FAFC",
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 40,
        paddingBottom: 20,
        backgroundColor: "#5E72E4",
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
    },
    headerLeft: {
        flexDirection: "row",
        alignItems: "center",
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: "#FFF",
        marginLeft: 15,
    },
    container: {
        paddingBottom: 100, // Added space for footer
    },
     scrollContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 100,
  },
    profileImageContainer: {
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 20,
    },
    profileInfoContainer: {
        paddingHorizontal: 20,
    },
    infoCard: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 20,
        marginBottom: 20,
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 3,
    },
    name: {
        fontSize: 22,
        fontWeight: "600",
        color: "#2D3748",
        marginBottom: 4,
        textAlign: "center",
    },
    email: {
        fontSize: 16,
        color: "#718096",
        marginBottom: 20,
        textAlign: "center",
    },
    infoSection: {
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: "600",
        color: "#4A5568",
        marginBottom: 12,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: "#EDF2F7",
    },
    infoItem: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    infoText: {
        fontSize: 15,
        color: "#4A5568",
        marginLeft: 12,
        flex: 1,
    },
    logoutButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#F56565",
        padding: 14,
        borderRadius: 8,
        marginTop: 20,
    },
    logoutButtonText: {
        color: "#FFF",
        fontSize: 16,
        fontWeight: "600",
        marginLeft: 8,
    },
    bottomBar: {
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
        paddingVertical: 12,
        paddingBottom: Platform.OS === "ios" ? 30 : 12,
        backgroundColor: "#fff",
        borderTopWidth: 1,
        borderTopColor: "#e0e0e0",
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
    },
    bottomButton: {
        justifyContent: "center",
        alignItems: "center",
        padding: 8,
    },
    bottomButtonActive: {
        marginTop: -25,
        backgroundColor: "#5E72E4",
        borderRadius: 15,
        paddingVertical: 10,
        paddingHorizontal: 20,
        shadowColor: "#5E72E4",
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    },
    bottomButtonIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#EBF4FF",
    },
    bottomButtonIconActive: {
        backgroundColor: "rgba(255, 255, 255, 0.2)",
    },
    bottomButtonText: {
        fontSize: 12,
        fontWeight: "500",
        color: "#718096",
        marginTop: 4,
    },
    bottomButtonTextActive: {
        color: "#FFF",
    },
});