import { StyleSheet, Platform, Dimensions, StatusBar } from "react-native";

const { width } = Dimensions.get("window");
const CARD_WIDTH = width - 32;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F7FAFC",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F7FAFC",
  },
  authContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#F7FAFC",
  },
  notesContainer: {
    backgroundColor: "#EDF2F7",
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
    marginBottom: 8,
  },
  authText: {
    fontSize: 18,
    marginBottom: 20,
    color: "#2D3748",
  },
  loginButton: {
    backgroundColor: "#5E72E4",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 6,
  },
  loginButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "600",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 40,
    paddingBottom: 20,
    backgroundColor: "#5E72E4",
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#FFF",
  },
  scrollContainer: {
    paddingBottom: 32,
  },
  section: {
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2D3748",
    marginBottom: 12,
  },
  photoButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  photoButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFF",
    width: "48%",
  },
  photoButtonActive: {
    backgroundColor: "#5E72E4",
    borderColor: "#5E72E4",
  },
  photoButtonText: {
    marginLeft: 8,
    fontSize: 16,
    color: "#5E72E4",
    fontWeight: "500",
  },
  photoButtonTextActive: {
    color: "#FFF",
  },
  previewContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  imagePreviewWrapper: {
    width: "48%",
    position: "relative",
  },
  previewLabel: {
    fontSize: 14,
    color: "#4A5568",
    marginBottom: 4,
  },
  imagePreview: {
    width: "100%",
    height: 150,
    borderRadius: 8,
  },
  clearButton: {
    position: "absolute",
    top: 20,
    right: 4,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 12,
    padding: 4,
  },
  instructionText: {
    fontSize: 14,
    color: "#718096",
    textAlign: "center",
    marginVertical: 8,
  },
  notesInput: {
    minHeight: 100,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: "#2D3748",
    backgroundColor: "#FFF",
  },
  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#5E72E4",
    paddingVertical: 14,
    borderRadius: 8,
    marginHorizontal: 16,
    marginTop: 16,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  emptyState: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 32,
  },
  emptyText: {
    fontSize: 16,
    color: "#A0AEC0",
    marginTop: 8,
  },
  photoCard: {
    minHeight: 100,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: "#2D3748",
    backgroundColor: "#FFF",
    marginBottom: 12,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  dateBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#5E72E4",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  dateText: {
    color: "#FFF",
    fontSize: 12,
    marginLeft: 4,
  },
  photoGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  photoContainer: {
    width: "48%",
  },
  photoLabel: {
    fontSize: 14,
    color: "#4A5568",
    marginBottom: 4,
  },
  photoImage: {
    width: "100%",
    height: 150,
    borderRadius: 8,
  },
  placeholder: {
    width: "100%",
    height: 150,
    borderRadius: 8,
    backgroundColor: "#EDF2F7",
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    fontSize: 12,
    color: "#A0AEC0",
    marginTop: 4,
  },
  notesBadge: {
    backgroundColor: "#EDF2F7",
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  notesUserName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2D3748",
    marginBottom: 4,
  },
  notesText: {
    fontSize: 14,
    color: "#4A5568",
  },
  actionButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    width: "48%",
  },
  saveButton: {
    backgroundColor: "#5E72E4",
  },
  deleteButton: {
    backgroundColor: "#E53E3E",
  },
  actionButtonText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 8,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  fullImage: {
    width: "90%",
    height: "80%",
  },
  closeButton: {
    position: "absolute",
    top: 40,
    right: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 20,
    padding: 8,
  },
});
