/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bill`; params?: Router.UnknownInputParams; } | { pathname: `/completed`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/notification`; params?: Router.UnknownInputParams; } | { pathname: `/order`; params?: Router.UnknownInputParams; } | { pathname: `/pending`; params?: Router.UnknownInputParams; } | { pathname: `/service`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/userphotos`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/home`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/notificationpage`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/PhotoComparisonPage`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/userbill`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/usercompleted`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/userpending`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/userprofile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bill`; params?: Router.UnknownOutputParams; } | { pathname: `/completed`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/notification`; params?: Router.UnknownOutputParams; } | { pathname: `/order`; params?: Router.UnknownOutputParams; } | { pathname: `/pending`; params?: Router.UnknownOutputParams; } | { pathname: `/service`; params?: Router.UnknownOutputParams; } | { pathname: `/user`; params?: Router.UnknownOutputParams; } | { pathname: `/userphotos`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/userapp/home`; params?: Router.UnknownOutputParams; } | { pathname: `/userapp/notificationpage`; params?: Router.UnknownOutputParams; } | { pathname: `/userapp/PhotoComparisonPage`; params?: Router.UnknownOutputParams; } | { pathname: `/userapp/userbill`; params?: Router.UnknownOutputParams; } | { pathname: `/userapp/usercompleted`; params?: Router.UnknownOutputParams; } | { pathname: `/userapp/userpending`; params?: Router.UnknownOutputParams; } | { pathname: `/userapp/userprofile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/bill${`?${string}` | `#${string}` | ''}` | `/completed${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/notification${`?${string}` | `#${string}` | ''}` | `/order${`?${string}` | `#${string}` | ''}` | `/pending${`?${string}` | `#${string}` | ''}` | `/service${`?${string}` | `#${string}` | ''}` | `/user${`?${string}` | `#${string}` | ''}` | `/userphotos${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/userapp/home${`?${string}` | `#${string}` | ''}` | `/userapp/notificationpage${`?${string}` | `#${string}` | ''}` | `/userapp/PhotoComparisonPage${`?${string}` | `#${string}` | ''}` | `/userapp/userbill${`?${string}` | `#${string}` | ''}` | `/userapp/usercompleted${`?${string}` | `#${string}` | ''}` | `/userapp/userpending${`?${string}` | `#${string}` | ''}` | `/userapp/userprofile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bill`; params?: Router.UnknownInputParams; } | { pathname: `/completed`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/notification`; params?: Router.UnknownInputParams; } | { pathname: `/order`; params?: Router.UnknownInputParams; } | { pathname: `/pending`; params?: Router.UnknownInputParams; } | { pathname: `/service`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/userphotos`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/home`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/notificationpage`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/PhotoComparisonPage`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/userbill`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/usercompleted`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/userpending`; params?: Router.UnknownInputParams; } | { pathname: `/userapp/userprofile`; params?: Router.UnknownInputParams; };
    }
  }
}
